routes/web.php
<?php

require __DIR__.'/web/pages.php';
require __DIR__.'/web/users.php';
require __DIR__.'/web/references.php';
require __DIR__.'/web/account.php';
require __DIR__.'/web/projects.php';
require __DIR__.'/web/payments.php';
require __DIR__.'/web/reports.php';
require __DIR__.'/web/invoices.php';
require __DIR__.'/web/calendar.php';

Route::group(['middleware' => ['role:admin']], function () {
    /*
     * Subscriptions Routes
     */
    Route::resource('subscriptions', 'SubscriptionsController');

    /*
     * Backup Restore Database Routes
     */
    Route::post('backups/upload', ['as' => 'backups.upload', 'uses' => 'BackupsController@upload']);
    Route::post('backups/{fileName}/restore', ['as' => 'backups.restore', 'uses' => 'BackupsController@restore']);
    Route::get('backups/{fileName}/dl', ['as' => 'backups.download', 'uses' => 'BackupsController@download']);
    Route::resource('backups', 'BackupsController', ['except' => ['create', 'show', 'edit']]);

    /*
     * Customers Routes
     */
    Route::get('customers/{customer}/projects', ['as' => 'customers.projects', 'uses' => 'Customers\ProjectsController@index']);
    Route::get('customers/{customer}/payments', ['as' => 'customers.payments', 'uses' => 'Customers\PaymentsController@index']);
    Route::get('customers/{customer}/subscriptions', ['as' => 'customers.subscriptions', 'uses' => 'Customers\SubscriptionsController@index']);
    Route::get('customers/{customer}/invoices', ['as' => 'customers.invoices', 'uses' => 'Customers\InvoicesController@index']);
    Route::resource('customers', 'Partners\CustomersController');

    /*
     * Vendors Routes
     */
    Route::apiResource('vendors', 'Partners\VendorsController');
});

app/Http/Controllers/Api/ProjectsController.php
<?php

namespace App\Http\Controllers\Api;

use App\Entities\Projects\ProjectsRepository;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

/**
 * Projects Controller.
 *
 * @author Nafies Luthfi <nafiesl@gmail.com>
 */
class ProjectsController extends Controller
{
    private $repo;

    public function __construct(ProjectsRepository $repo)
    {
        $this->repo = $repo;
    }

    public function index(Request $request)
    {
        return $this->repo->getProjects($request->get('q'), $request->get('status_id'), auth()->user());
    }

    public function show($id)
    {
        return $this->repo->requireById($id);
    }

    public function jobs($id)
    {
        $project = $this->repo->requireById($id);
        $response = fractal()
            ->item($project->toArray())
            ->transformWith(function ($project) {
                return $project;
            })
            ->toArray();

        return $response;
    }
}

app/Http/Controllers/Customers/ProjectsController.php
<?php

namespace App\Http\Controllers\Customers;

use App\Entities\Partners\Customer;
use App\Http\Controllers\Controller;

/**
 * Customer Projects Controller.
 *
 * @author Nafies Luthfi <nafiesL@gmail.com>
 */
class ProjectsController extends Controller
{
    /**
     * Project list of a customer.
     *
     * @param  \App\Entities\Partners\Customer $customer
     * @return \Illuminate\View\View
     */
    public function index(Customer $customer)
    {
        $projects = $customer->projects;

        return view('customers.projects', compact('customer', 'projects'));
    }
}

app/Http/Controllers/Issues/CommentController.php
<?php

namespace App\Http\Controllers\Issues;

use App\Entities\Projects\Comment;
use App\Entities\Projects\Issue;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class CommentController extends Controller
{
    /**
     * Store a new comment in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Entities\Projects\Issue  $issue
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request, Issue $issue)
    {
        $this->authorize('comment-on', $issue);

        $newComment = $request->validate([
            'body' => 'required|string|max:255',
        ]);

        $issue->comments()->create([
            'body'       => $newComment['body'],
            'creator_id' => auth()->id(),
        ]);
        $issue->touch();

        flash(__('comment.created'), 'success');

        return back();
    }

    /**
     * Update the specified comment.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Entities\Projects\Issue  $issue
     * @param  \App\Entities\Projects\Comment  $comment
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Issue $issue, Comment $comment)
    {
        $this->authorize('update', $comment);

        $commentData = $request->validate([
            'body' => 'required|string|max:255',
        ]);
        $comment->update($commentData);
        flash(__('comment.updated'), 'success');

        return redirect()->route('projects.issues.show', [$issue->project, $issue]);
    }

    /**
     * Remove the specified comment.
     *
     * @param  \App\Entities\Projects\Issue  $issue
     * @param  \\App\Entities\Projects\Comment  $comment
     * @return \Illuminate\Routing\Redirector
     */
    public function destroy(Issue $issue, Comment $comment)
    {
        $this->authorize('delete', $comment);

        request()->validate([
            'comment_id' => 'required|exists:comments,id',
        ]);

        if (request('comment_id') == $comment->id && $comment->delete()) {
            flash(__('comment.deleted'), 'warning');

            return redirect()->route('projects.issues.show', [$issue->project, $issue]);
        }
        flash(__('comment.undeleted'), 'error');

        return back();
    }
}

app/Http/Controllers/Issues/OptionController.php
<?php

namespace App\Http\Controllers\Issues;

use App\Entities\Projects\Issue;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class OptionController extends Controller
{
    public function update(Request $request, Issue $issue)
    {
        $issueData = $request->validate([
            'priority_id' => 'required|in:1,2,3',
            'status_id'   => 'required|in:0,1,2,3,4',
            'pic_id'      => 'nullable|exists:users,id',
        ]);
        $issue->priority_id = $issueData['priority_id'];
        $issue->status_id = $issueData['status_id'];
        $issue->pic_id = $issueData['pic_id'];
        $issue->save();
        flash(__('issue.updated'), 'success');

        return back();
    }
}

app/Http/Controllers/Projects/CommentsController.php
<?php

namespace App\Http\Controllers\Projects;

use App\Entities\Projects\Comment;
use App\Entities\Projects\Project;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class CommentsController extends Controller
{
    /**
     * Display a listing of the project comments.
     *
     * @param  \App\Entities\Projects\Project  $project
     * @return \Illuminate\View\View
     */
    public function index(Project $project)
    {
        $this->authorize('view-comments', $project);

        $editableComment = null;
        $comments = $project->comments()->with('creator')->latest()->paginate();

        if (request('action') == 'comment-edit' && request('comment_id') != null) {
            $editableComment = Comment::find(request('comment_id'));
        }

        return view('projects.comments', compact('project', 'comments', 'editableComment'));
    }

    /**
     * Store a new comment in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Entities\Projects\Project  $project
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request, Project $project)
    {
        $this->authorize('comment-on', $project);

        $newComment = $request->validate([
            'body' => 'required|string|max:255',
        ]);

        $project->comments()->create([
            'body'       => $newComment['body'],
            'creator_id' => auth()->id(),
        ]);

        flash(__('comment.created'), 'success');

        return back();
    }

    /**
     * Update the specified comment.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Entities\Projects\Project  $project
     * @param  \App\Entities\Projects\Comment  $comment
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Project $project, Comment $comment)
    {
        $this->authorize('update', $comment);

        $commentData = $request->validate([
            'body' => 'required|string|max:255',
        ]);
        $comment->update($commentData);
        flash(__('comment.updated'), 'success');

        return redirect()->route('projects.comments.index', [$project] + request(['page']));
    }

    /**
     * Remove the specified comment.
     *
     * @param  \App\Entities\Projects\Comment  $comment
     * @return \Illuminate\Routing\Redirector
     */
    public function destroy(Project $project, Comment $comment)
    {
        $this->authorize('delete', $comment);

        request()->validate([
            'comment_id' => 'required|exists:comments,id',
        ]);

        if (request('comment_id') == $comment->id && $comment->delete()) {
            $routeParam = [$project] + request(['page']);
            flash(__('comment.deleted'), 'warning');

            return redirect()->route('projects.comments.index', $routeParam);
        }
        flash(__('comment.undeleted'), 'error');

        return back();
    }
}

app/Http/Controllers/Projects/FeesController.php
<?php

namespace App\Http\Controllers\Projects;

use App\Entities\Payments\Payment;
use App\Entities\Projects\Project;
use App\Entities\Users\User;
use App\Http\Controllers\Controller;

/**
 * Project Fees Controller.
 *
 * @author Nafies Luthfi <nafiesl@gmail.com>
 */
class FeesController extends Controller
{
    /**
     * Show create project fee form.
     *
     * @param  \App\Entities\Projects\Project  $project
     * @return \Illuminate\View\View
     */
    public function create(Project $project)
    {
        $this->authorize('create', new Payment());

        $partners = User::pluck('name', 'id')->all();

        return view('projects.fees.create', compact('project', 'partners'));
    }

    /**
     * Store new fee entry to the database.
     *
     * @param  \App\Entities\Projects\Project  $project
     * @return \Illuminate\Routing\Redirector
     */
    public function store(Project $project)
    {
        $this->authorize('create', new Payment());

        $newPaymentData = request()->validate([
            'type_id'     => 'required|numeric',
            'date'        => 'required|date',
            'amount'      => 'required|numeric',
            'partner_id'  => 'required|exists:users,id',
            'description' => 'required|string',
        ]);
        $newPaymentData['in_out'] = 0;
        $newPaymentData['project_id'] = $project->id;
        $newPaymentData['partner_type'] = User::class;

        Payment::create($newPaymentData);

        flash(trans('payment.created'), 'success');

        return redirect()->route('projects.payments', $project->id);
    }
}

app/Http/Controllers/Projects/InvoicesController.php
<?php

namespace App\Http\Controllers\Projects;

use App\Entities\Projects\Project;
use App\Http\Controllers\Controller;

/**
 * Project Invoices Controller.
 *
 * @author Nafies Luthfi <nafiesL@gmail.com>
 */
class InvoicesController extends Controller
{
    /**
     * Invoice list of a project.
     *
     * @param  \App\Entities\Projects\Project  $project
     * @return \Illuminate\View\View
     */
    public function index(Project $project)
    {
        $this->authorize('view-invoices', $project);

        $invoices = $project->invoices()->orderBy('date', 'desc')->get();

        return view('projects.invoices', compact('project', 'invoices'));
    }
}

app/Http/Controllers/Projects/IssueController.php
<?php

namespace App\Http\Controllers\Projects;

use App\Entities\Projects\Comment;
use App\Entities\Projects\Issue;
use App\Entities\Projects\IssueStatus;
use App\Entities\Projects\Priority;
use App\Entities\Projects\Project;
use App\Entities\Users\User;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class IssueController extends Controller
{
    public function index(Project $project)
    {
        $issueQuery = $project->issues()
            ->orderBy('updated_at', 'desc')
            ->with(['pic', 'creator'])
            ->withCount(['comments']);

        if ($priorityId = request('priority_id')) {
            $issueQuery->where('priority_id', $priorityId);
        }

        if ($statusId = request('status_id')) {
            $issueQuery->where('status_id', $priorityId);
        }

        $issues = $issueQuery->get();

        return view('projects.issues.index', compact('project', 'issues'));
    }

    public function create(Project $project)
    {
        $users = User::pluck('name', 'id');
        $priorities = Priority::toArray();

        return view('projects.issues.create', compact('project', 'users', 'priorities'));
    }

    public function store(Request $request, Project $project)
    {
        $issueData = $request->validate([
            'title'       => 'required|max:60',
            'body'        => 'required|max:255',
            'priority_id' => 'required|in:1,2,3',
            'pic_id'      => 'nullable|exists:users,id',
        ]);
        Issue::create([
            'project_id'  => $project->id,
            'creator_id'  => auth()->id(),
            'title'       => $issueData['title'],
            'body'        => $issueData['body'],
            'priority_id' => $issueData['priority_id'],
            'pic_id'      => $issueData['pic_id'],
        ]);
        flash(__('issue.created'), 'success');

        return redirect()->route('projects.issues.index', $project);
    }

    public function show(Project $project, Issue $issue)
    {
        $editableComment = null;
        $priorities = Priority::toArray();
        $statuses = IssueStatus::toArray();
        $users = User::pluck('name', 'id');
        $comments = $issue->comments()->with('creator')->get();

        if (request('action') == 'comment-edit' && request('comment_id') != null) {
            $editableComment = Comment::find(request('comment_id'));
        }

        return view('projects.issues.show', compact(
            'project', 'issue', 'users', 'statuses', 'priorities', 'comments',
            'editableComment'
        ));
    }

    public function edit(Project $project, Issue $issue)
    {
        return view('projects.issues.edit', compact('project', 'issue'));
    }

    public function update(Request $request, Project $project, Issue $issue)
    {
        $issueData = $request->validate([
            'title' => 'required|max:60',
            'body'  => 'required|max:255',
        ]);
        $issue->title = $issueData['title'];
        $issue->body = $issueData['body'];
        $issue->save();

        flash(__('issue.updated'), 'success');

        return redirect()->route('projects.issues.show', [$project, $issue]);
    }

    public function destroy(Request $request, Project $project, Issue $issue)
    {
        $request->validate(['issue_id' => 'required']);

        if ($request->get('issue_id') == $issue->id && $issue->delete()) {
            flash(__('issue.deleted'), 'warning');

            return redirect()->route('projects.issues.index', $project);
        }
        flash(__('issue.undeleted'), 'danger');

        return back();
    }
}

app/Http/Controllers/Users/ProjectsController.php
<?php

namespace App\Http\Controllers\Users;

use App\Entities\Users\User;
use App\Http\Controllers\Controller;

/**
 * User Projects Controller.
 *
 * @author Nafies Luthfi <nafiesl@gmail.com>
 */
class ProjectsController extends Controller
{
    public function index(User $user)
    {
        $projects = $user->projects()
            ->where(function ($query) {
                $query->where('projects.name', 'like', '%'.request('q').'%');
                $query->where('status_id', request('status', 2));
            })
            ->latest()
            ->with(['customer'])
            ->paginate();

        return view('users.projects', compact('user', 'projects'));
    }
}

resources/views/projects/issues/create.blade.php
@extends('layouts.project')

@section('subtitle', __('issue.create'))

@section('action-buttons')
@can('create', new App\Entities\Projects\Issue)
    {!! html_link_to_route('projects.issues.create', __('issue.create'), $project, ['class' => 'btn btn-success', 'icon' => 'plus']) !!}
@endcan
@endsection

@section('content-project')

<div class="row">
    <div class="col-sm-6 col-sm-offset-2">
        {{ Form::open(['route' => ['projects.issues.store', $project]]) }}
        <div class="panel panel-default">
            <div class="panel-heading"><h3 class="panel-title">{{ __('issue.create') }}</h3></div>
            <div class="panel-body">
                {!! FormField::text('title', ['label' => __('issue.title')]) !!}
                {!! FormField::textarea('body', ['label' => __('issue.body')]) !!}
                {!! FormField::radios('priority_id', $priorities, ['label' => __('issue.priority'), 'placeholder' => false]) !!}
                {!! FormField::select('pic_id', $users, ['label' => __('issue.pic')]) !!}
            </div>
            <div class="panel-footer">
                {{ Form::submit(__('issue.create'), ['class' => 'btn btn-success']) }}
                {{ link_to_route('projects.issues.index', __('app.cancel'), $project, ['class' => 'btn btn-default']) }}
            </div>
        </div>
        {{ Form::close() }}
    </div>
</div>
@endsection

resources/views/projects/issues/edit.blade.php
@extends('layouts.project')

@section('subtitle', __('issue.update'))

@section('action-buttons')
@can('create', new App\Entities\Projects\Issue)
    {!! html_link_to_route('projects.issues.create', __('issue.create'), $project, ['class' => 'btn btn-success', 'icon' => 'plus']) !!}
@endcan
@endsection

@section('content-project')
<div class="row">
    <div class="col-sm-6 col-sm-offset-2">
        @if (request('action') == 'delete' && $issue)
            <div class="panel panel-default">
                <div class="panel-heading"><h3 class="panel-title">{{ __('issue.delete') }}</h3></div>
                <div class="panel-body">
                    <label class="control-label text-primary">{{ __('issue.title') }}</label>
                    <p>{{ $issue->title }}</p>
                    <label class="control-label text-primary">{{ __('issue.body') }}</label>
                    <p>{{ $issue->body }}</p>
                    {!! $errors->first('issue_id', '<span class="form-error small">:message</span>') !!}
                </div>
                <hr style="margin:0">
                <div class="panel-body text-danger">{{ __('issue.delete_confirm') }}</div>
                <div class="panel-footer">
                    {!! FormField::delete(
                        ['route' => ['projects.issues.destroy', $project, $issue]],
                        __('app.delete_confirm_button'),
                        ['id' => 'delete-issue-'.$issue->id, 'class' => 'btn btn-danger'],
                        ['issue_id' => $issue->id]
                    ) !!}
                    {{ link_to_route('projects.issues.edit', __('app.cancel'), [$project, $issue], ['class' => 'btn btn-default']) }}
                </div>
            </div>
        @else
            {{ Form::model($issue, ['route' => ['projects.issues.update', $project, $issue], 'method' => 'patch']) }}
            <div class="panel panel-default">
                <div class="panel-heading"><h3 class="panel-title">{{ __('issue.update') }}</h3></div>
                <div class="panel-body">
                    {!! FormField::text('title', ['label' => __('issue.title')]) !!}
                    {!! FormField::textarea('body', ['label' => __('issue.body')]) !!}
                </div>
                <div class="panel-footer">
                    {{ Form::submit(__('issue.update'), ['class' => 'btn btn-success']) }}
                    {{ link_to_route('projects.issues.show', __('app.cancel'), [$project, $issue], ['class' => 'btn btn-default']) }}
                    {{ link_to_route('projects.issues.edit', __('app.delete'), [$project, $issue, 'action' => 'delete'], ['id' => 'delete-issue-'.$issue->id, 'class' => 'btn btn-danger pull-right']) }}
                </div>
            </div>
            {{ Form::close() }}
        @endif
    </div>
</div>
@endsection

resources/views/projects/issues/index.blade.php
@inject('priorities', 'App\Entities\Projects\Priority')
@inject('issueStatuses', 'App\Entities\Projects\IssueStatus')
@extends('layouts.project')

@section('subtitle', __('project.issues'))

@section('action-buttons')
{{ Form::open(['method' => 'get', 'class' => 'form-inline', 'style' => 'display:inline']) }}
{!! FormField::select('priority_id', $priorities::toArray(), ['label' => false, 'placeholder' => __('issue.all_priority'), 'value' => request('priority_id')]) !!}
{!! FormField::select('status_id', $issueStatuses::toArray(), ['label' => false, 'placeholder' => __('issue.all_status'), 'value' => request('status_id')]) !!}
{{ Form::submit(__('app.filter'), ['class' => 'btn btn-info']) }}
@if (request(['priority_id', 'status_id']))
    {{ link_to_route('projects.issues.index', __('app.reset'), $project, ['class' => 'btn btn-default']) }}
@endif
{{ Form::close() }}
@can('create', new App\Entities\Projects\Issue)
    {!! html_link_to_route('projects.issues.create', __('issue.create'), $project, ['class' => 'btn btn-success', 'icon' => 'plus']) !!}
@endcan
@endsection

@section('content-project')
<div id="project-issues" class="panel panel-default table-responsive">
    <div class="panel-heading">
        <h3 class="panel-title">{{ __('project.issues') }}</h3>
    </div>
    <table class="table table-condensed table-striped">
        <thead>
            <th>{{ __('app.table_no') }}</th>
            <th>{{ __('issue.title') }}</th>
            <th>{{ __('issue.priority') }}</th>
            <th>{{ __('app.status') }}</th>
            <th class="text-center">{{ __('comment.comment') }}</th>
            <th>{{ __('issue.pic') }}</th>
            <th>{{ __('issue.creator') }}</th>
            <th>{{ __('app.last_update') }}</th>
            <th class="text-center">{{ __('app.action') }}</th>
        </thead>
        <tbody>
            @forelse($issues as $key => $issue)
            @php
            $no = 1 + $key;
            @endphp
            <tr id="{{ $issue->id }}">
                <td>{{ $no }}</td>
                <td>{{ $issue->title }}</td>
                <td>{!! $issue->priority_label !!}</td>
                <td>{!! $issue->status_label !!}</td>
                <td class="text-center">{{ $issue->comments_count }}</td>
                <td>{{ $issue->pic->name }}</td>
                <td>{{ $issue->creator->name }}</td>
                <td>{{ $issue->updated_at->diffForHumans() }}</td>
                <td class="text-center">
                    {{ link_to_route(
                        'projects.issues.show',
                        __('app.show'),
                        [$project, $issue],
                        ['title' => __('issue.show')]
                    ) }}
                </td>
            </tr>
            @empty
            <tr><td colspan="9">{{ __('issue.not_found') }}</td></tr>
            @endforelse
        </tbody>
    </table>
</div>
@endsection

resources/views/projects/issues/show.blade.php
@extends('layouts.project')

@section('subtitle', __('issue.detail'))

@section('action-buttons')
@can('create', new App\Entities\Projects\Issue)
    {!! html_link_to_route('projects.issues.create', __('issue.create'), $project, ['class' => 'btn btn-success', 'icon' => 'plus']) !!}
@endcan
@endsection

@section('content-project')
<div class="row">
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">
                    <div class="pull-right">{!! $issue->status_label !!}</div>
                    {{ __('issue.detail') }}
                </h3>
            </div>
            <table class="table table-condensed">
                <tbody>
                    <tr><th class="col-md-4">{{ __('issue.title') }}</th><td class="col-md-8">{{ $issue->title }}</td></tr>
                    <tr><th>{{ __('issue.body') }}</th><td>{{ $issue->body }}</td></tr>
                    <tr><th>{{ __('issue.priority') }}</th><td>{!! $issue->priority_label !!}</td></tr>
                    <tr><th>{{ __('issue.pic') }}</th><td>{{ $issue->pic->name }}</td></tr>
                    <tr><th>{{ __('app.created_by') }}</th><td>{{ $issue->creator->name }}</td></tr>
                </tbody>
            </table>
            <div class="panel-footer">
                {{ link_to_route('projects.issues.edit', __('issue.edit'), [$project, $issue], ['id' => 'edit-issue-'.$issue->id, 'class' => 'btn btn-warning']) }}
                {{ link_to_route('projects.issues.index', __('issue.back_to_index'), [$project], ['class' => 'btn btn-default pull-right']) }}
            </div>
        </div>
        <hr>
        @include('projects.issues.partials.comment-section')
    </div>
    <div class="col-md-6">
        {{ Form::model($issue, ['route' => ['issues.options.update', $issue], 'method' => 'patch']) }}
        <div class="panel panel-default">
            <div class="panel-heading"><h3 class="panel-title">{{ __('app.action') }}</h3></div>
            <div class="panel-body">
                {!! FormField::radios('priority_id', $priorities, ['label' => __('issue.priority')]) !!}
                {!! FormField::radios('status_id', $statuses, ['label' => __('app.status')]) !!}
                {!! FormField::select('pic_id', $users, ['label' => __('issue.assign_pic'), 'placeholder' => __('issue.select_pic')]) !!}
            </div>
            <div class="panel-footer">
                {{ Form::submit(__('issue.update'), ['class' => 'btn btn-success']) }}
            </div>
        </div>
        {{ Form::close() }}
    </div>
</div>
@endsection

@section('script')
<script>
(function () {
    $('#commentModal').modal({
        show: true,
        backdrop: 'static',
    });
})();
</script>
@endsection