routes/web.php
<?php

require __DIR__.'/web/pages.php';
require __DIR__.'/web/users.php';
require __DIR__.'/web/references.php';
require __DIR__.'/web/account.php';
require __DIR__.'/web/projects.php';
require __DIR__.'/web/payments.php';
require __DIR__.'/web/reports.php';
require __DIR__.'/web/invoices.php';
require __DIR__.'/web/calendar.php';

Route::group(['middleware' => ['role:admin']], function () {
    /*
     * Subscriptions Routes
     */
    Route::resource('subscriptions', 'SubscriptionsController');

    /*
     * Backup Restore Database Routes
     */
    Route::post('backups/upload', ['as' => 'backups.upload', 'uses' => 'BackupsController@upload']);
    Route::post('backups/{fileName}/restore', ['as' => 'backups.restore', 'uses' => 'BackupsController@restore']);
    Route::get('backups/{fileName}/dl', ['as' => 'backups.download', 'uses' => 'BackupsController@download']);
    Route::resource('backups', 'BackupsController', ['except' => ['create', 'show', 'edit']]);

    /*
     * Customers Routes
     */
    Route::get('customers/{customer}/projects', ['as' => 'customers.projects', 'uses' => 'Customers\ProjectsController@index']);
    Route::get('customers/{customer}/payments', ['as' => 'customers.payments', 'uses' => 'Customers\PaymentsController@index']);
    Route::get('customers/{customer}/subscriptions', ['as' => 'customers.subscriptions', 'uses' => 'Customers\SubscriptionsController@index']);
    Route::get('customers/{customer}/invoices', ['as' => 'customers.invoices', 'uses' => 'Customers\InvoicesController@index']);
    Route::resource('customers', 'Partners\CustomersController');

    /*
     * Vendors Routes
     */
    Route::apiResource('vendors', 'Partners\VendorsController');
});

resources/views/pages/about.blade.php
@extends('layouts.guest')

@section('content')
<h1 class="page-header">Aplikasi ...</h1>
<div class="row">
    <div class="col-lg-6">
        <div class="panel panel-success">
            <div class="panel-heading"><h3 class="panel-title"><i class="fa fa-info fa-fw"></i> Tentang Aplikasi</h3></div>
            <div class="panel-body">
                <p>Ini adalah starter kit untuk membuat aplikasi berbasis Web dengan <strong>Laravel 5.2</strong>.</p>
                <p>
                    Pada aplikasi ini terdapat beberapa fitur dasar biasa digunakan untuk aplikasi Web :
                    <ol>
                        <li>Autentikasi User
                            <ul>
                                <li>Login</li>
                                <li>Logout</li>
                                <li>Register</li>
                                <li>Ganti Password</li>
                                <li>Lupa Password</li>
                            </ul>
                        </li>
                        <li>b</li>
                        <li>c</li>
                        <li>d</li>
                    </ol>
                </p>
                <p>Aplikasi ini dibuat dengan mempertimbangkan kemudahan penggunaan, mempermudah proses transaksi, minimalisir kemungkinan kesalahan input dengan fitur validasi data sebelum menyimpan ke dalam database.</p>
                <p>Aplikasi ini dapat dikembangkan lebih lanjut dengan fitur-fitur baru menyesuaikan kebutuhan.</p>
            </div>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="panel panel-info">
            <div class="panel-heading"><h3 class="panel-title">Tentang Pengembang Aplikasi</h3></div>
            <div class="panel-body">
                <p>
                    Aplikasi ini dibuat oleh:
                    <table class="table">
                        <tbody>
                            <tr><td>Nama</td><td>:</td><td>Nafies Luthfi</td></tr>
                            <tr><td>Kontak</td><td>:</td><td>0817-532-654</td></tr>
                            <tr><td>Email</td><td>:</td><td>nafiesL@gmail.com</td></tr>
                            <tr><td>Website</td><td>:</td><td><a href="http://jasawebsitebanjarmasin.com" target="_blank">JasaWebsiteBanjarmasin.com</a></td></tr>
                            <tr><td>Alamat</td><td>:</td><td>Jln. Pramuka, Gg. Mawar, Rt. 09, No. 60, Kel. Pemurus Luar, Kec. Banjarmasin Timur, Kota Banjarmasin - 70249</td></tr>
                        </tbody>
                    </table>
                </p>
                <p>Silakan menghubungi saya untuk pembuatan website, aplikasi berbasis web, blog, dan jasa SEO (menjadikan website anda terindex pada halaman 1 di mesin mencari google).</p>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/pages/home.blade.php
@extends('layouts.dashboard')

@section('title', __('nav_menu.dashboard'))

@section('content-dashboard')
@if (auth()->user()->hasRole('admin'))
<div class="row">
    <div class="col-lg-5">
        <legend style="border-bottom: none" class="text-center">{{ __('dashboard.project_status_stats') }}</legend>
        <div class="row">
            @foreach(ProjectStatus::all() as $statusId => $status)
            <div class="col-lg-6 col-md-4 col-xs-6">
                @include('view-components.dashboard-panel', [
                    'class' => ProjectStatus::getColorById($statusId),
                    'icon' => ProjectStatus::getIconById($statusId),
                    'number' => array_key_exists($statusId, $projectStatusStats) ? $projectStatusStats[$statusId] : 0,
                    'text' => ProjectStatus::getNameById($statusId),
                    'linkRoute' => route('projects.index', ['status_id' => $statusId]),
                ])
            </div>
            @endforeach
        </div>
    </div>
    <div class="col-lg-7">
        <legend style="border-bottom: none" class="text-center">{{ __('dashboard.earnings_stats') }}</legend>
        <div class="panel panel-default table-responsive hidden-xs">
            <table class="table table-condensed table-bordered">
                <tr>
                    <td class="col-xs-2 text-center">{{ __('dashboard.yearly_earnings') }} ({{ $queriedYear }})</td>
                    <td class="col-xs-2 text-center">{{ __('dashboard.finished_projects_count') }} ({{ $queriedYear }})</td>
                    <td class="col-xs-2 text-center">{{ __('dashboard.receiveable_earnings') }}</td>
                </tr>
                <tr>
                    <td class="text-center text-primary lead" style="border-top: none;">
                        {{ $totalEarnings = format_money(AdminDashboard::totalEarnings($queriedYear)) }}
                    </td>
                    <td class="text-center text-primary lead" style="border-top: none;">
                        {{ $totalFinishedProjects = AdminDashboard::totalFinishedProjects($queriedYear) }} Projects
                    </td>
                    <td class="text-center text-primary lead" style="border-top: none;">
                        {{ $currentOutstandingCustomerPayment = format_money(AdminDashboard::currentOutstandingCustomerPayment($queriedYear)) }}
                    </td>
                </tr>
            </table>
        </div>

        <ul class="list-group visible-xs">
            <li class="list-group-item">
                {{ __('dashboard.yearly_earnings') }} ({{ $queriedYear }})
                <span class="pull-right text-primary">{{ $totalEarnings }}</span>
            </li>
            <li class="list-group-item">
                {{ __('dashboard.finished_projects_count') }} ({{ $queriedYear }})
                <span class="pull-right text-primary">{{ $totalFinishedProjects }} Projects</span>
            </li>
            <li class="list-group-item">
                {{ __('dashboard.receiveable_earnings') }}
                <span class="pull-right text-primary">{{ $currentOutstandingCustomerPayment }}</span>
            </li>
        </ul>

        <legend style="border-bottom: none" class="text-center">{{ __('dashboard.upcoming_subscriptions_expiry') }}</legend>

        <div class="panel panel-default table-responsive">
            <table class="table table-condensed">
                <tr>
                    <th class="col-xs-3">{{ __('subscription.subscription') }}</th>
                    <th class="col-xs-3">{{ __('customer.customer') }}</th>
                    <th class="col-xs-3 text-right">{{ __('invoice.amount') }}</th>
                    <th class="col-xs-5 text-center">{{ __('subscription.due_date') }}</th>
                </tr>
                @forelse(AdminDashboard::upcomingSubscriptionDueDatesList() as $subscription)
                <tr>
                    <td>{{ $subscription->name_link }}</td>
                    <td>{{ $subscription->customer->name }}</td>
                    <td class="text-right">{{ format_money($subscription->price) }}</td>
                    <td class="text-center">
                        {{ $subscription->due_date }}
                        {!! $subscription->nearOfDueDateSign() !!}
                    </td>
                </tr>
                @empty
                <tr><td colspan="4">{{ __('dashboard.no_upcoming_subscriptions_expiry') }}</td></tr>
                @endforelse
                <tr><th colspan="4" class="text-center">{{ link_to_route('subscriptions.index', __('subscription.view_all')) }}</th></tr>
            </table>
        </div>
    </div>
</div>
@else
<div class="row">
    <div class="col-md-4 col-md-offset-3">
        <div class="panel panel-default">
            <div class="panel-heading"><h3 class="panel-title">{{ __('user.current_jobs') }}</h3></div>
            <table class="table table-condensed">
                <tbody>
                    @php
                        $currentJobTotal = 0;
                    @endphp
                    <tr>
                        <th class="text-center">{{ __('job.progress') }}</th>
                        <th class="text-center">{{ __('user.jobs_count') }}</th>
                    </tr>
                    <tr>
                        <td class="text-center">0 - 10%</td>
                        <td class="text-center">
                            {{ $count = $userCurrentJobs->filter(function ($job) {
                                return $job->progress == 0;
                            })->count() }}
                            @php
                                $currentJobTotal += $count;
                            @endphp
                        </td>
                    </tr>
                    <tr>
                        <td class="text-center">11 - 50%</td>
                        <td class="text-center">
                            {{ $count = $userCurrentJobs->filter(function ($job) {
                                return $job->progress > 10 && $job->progress <= 50;
                            })->count() }}
                            @php
                                $currentJobTotal += $count;
                            @endphp
                        </td>
                    </tr>
                    <tr>
                        <td class="text-center">51 - 75%</td>
                        <td class="text-center">
                            {{ $count = $userCurrentJobs->filter(function ($job) {
                                return $job->progress > 50 && $job->progress <= 75;
                            })->count() }}
                            @php
                                $currentJobTotal += $count;
                            @endphp
                        </td>
                    </tr>
                    <tr>
                        <td class="text-center">76 - 99%</td>
                        <td class="text-center">
                            {{ $count = $userCurrentJobs->filter(function ($job) {
                                return $job->progress > 75 && $job->progress <= 99;
                            })->count() }}
                            @php
                                $currentJobTotal += $count;
                            @endphp
                        </td>
                    </tr>
                    <tr>
                        <td class="text-center">100%</td>
                        <td class="text-center">
                            {{ $count = $userCurrentJobs->filter(function ($job) {
                                return $job->progress == 100;
                            })->count() }}
                            @php
                                $currentJobTotal += $count;
                            @endphp
                        </td>
                    </tr>
                </tbody>
                <tfoot>
                    <tr style="border-top: 4px solid #ccc">
                        <th class="text-center">{{ __('app.total') }}</th>
                        <th class="text-center">{{ $currentJobTotal }}</th>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>

@endif
@endsection